### ISSUE TITLE
h.SOLVESH/M_diagonalization_Lowdin.F90

### ISSUE THREAD

**Issue by dgtrabada** [thunder-dft/thunder-master#41]
If you want to compilate fireball or lightning.x with DOGS, KPOINTS and MCWEDA :
h.SOLVESH/M_diagonalization_Lowdin.F90(378): error #6404: This name does not have a type, and must have an explicit type.   [RWORK]
        allocate (rwork(lrwork))
------------------^
h.SOLVESH/M_diagonalization_Lowdin.F90(395): error #6404: This name does not have a type, and must have an explicit type.   [A0R]
        a0r = 0.0d0
--------^
h.SOLVESH/M_diagonalization_Lowdin.F90(396): error #6404: This name does not have a type, and must have an explicit type.   [A1R]
        a1r = 1.0d0
--------^

**Comment by psience-guy** [comment]
The code has gone through many iterations and this module is replaced with other modules related to which diagonalization is being used.
