### ISSUE TITLE
Update icc compiler to icx

### ISSUE THREAD

**Issue by renpj** [thunder-dft/thunder-master#42]
For latest intel oneapi compiler, there is no icc and icpc, and these compiler starts to be deprecated. Should FIREBALL update to icx? 

https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-icc-users-to-dpcpp-or-icx.html

**Comment by renpj** [comment]
And they are also planning to move from ifort to new fortran compiler ifx.
https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-ifort-to-ifx.html

**Comment by psience-guy** [comment]
I changed HKQAI file ifort to ifx and icc to icx. I did not change the ICC files because it's not certain how frequently they will update the compilers at the ICC - HPC.
